const roles = {
  MANAGE_MEMBER: "MANAGE_MEMBER",
  MANAGE_CUSTOMER: "MANAGE_CUSTOMER",
  MANAGE_AUTHOR: "MANAGE_AUTHOR",
  MANAGE_CATEGORY: "MANAGE_CATEGORY",
  MANAGE_BOOK: "MANAGE_BOOK",
  MANAG_ORDER: "MANAGE_ORDER",
};

module.exports = roles;
